<?php
set_time_limit(0);
error_reporting(0);
$list['front'] ="admin
adm
admincp
admcp
cp
modcp
moderatorcp
adminare
admins
cpanel
controlpanel";
$list['end'] = "ftflms/login 
users/login/ 
admin/users/login/ 
admin/user/ 
admin/
administrador/
administrador.php
honestadmin/
login.htm 
login.html 
login/ 
adm/ 
adm/login 
adm/login.php
log/ 
manager/ 
manager 
manager/login_fail.php?accesscheck=%2Fmanager%2Findex.php
aITdo/
admin1 
admin_panel 
myadmin.php 
admin112/
admin/account.html 
admin/login.html 
admin/login.htm 
admin/home 
admin/controlpanel.html 
admin/controlpanel.htm 
admin/cp 
admin/adminLogin.html 
admin/adminLogin.htm 
admin/admin_login 
admin/controlpanel 
admin/admin-login 
admin-login 
admin/account 
admin/admin 
admin.htm 
admin.html 
adminitem/ 
adminitem 
adminitems/ 
adminitems 
administrator/ 
administrator/login 
administrator 
administration/ 
administration 
adminLogin/ 
adminlogin 
admin_area/admin 
admin_area/ 
admin_area/login 
letmein/ 
letmein 
superuser/ 
superuser 
access/ 
access 
sysadm/ 
sysadm 
superman/ 
supervisor/ 
panel/ 
control/ 
control 
member/ 
member 
members/ 
members 
user/ 
user 
cp/ 
uvpanel/ 
manage/ 
manage 
management/ 
management 
signin/ 
signin 
log-in/ 
log-in 
log_in/ 
log_in 
sign_in/ 
sign_in 
sign-in/ 
sign-in 
users/ 
users 
accounts/ 
accounts 
wp-login.php 
bb-admin/login 
bb-admin/admin 
bb-admin/admin.html 
administrator/account 
relogin.htm 
relogin.html 
check 
relogin 
blog/wp-login 
user/admin 
users/admin 
registration/ 
processlogin 
checklogin 
checkuser 
checkadmin 
isadmin 
authenticate 
authentication 
auth 
authuser 
authadmin 
cp 
modelsearch/login 
moderator 
moderator/ 
controlpanel/ 
controlpanel 
admincontrol 
adminpanel 
fileadmin/ 
fileadmin 
sysadmin 
admin1 
admin1.html 
admin1.htm 
admin2 
admin2.html 
yonetim 
yonetim.html 
yonetici 
yonetici.html 
phpmyadmin/ 
myadmin/ 
ur-admin 
ur-admin/ 
Server 
Server/ 
wp-admin/ 
administr8 
administr8/ 
webadmin/ 
webadmin 
administratie/ 
admins/ 
admins 
administrivia/ 
Database_Administration/ 
useradmin/ 
sysadmins/ 
admin1/ 
system-administration/ 
administrators/ 
pgadmin/ 
directadmin/ 
staradmin/ 
ServerAdministrator/ 
SysAdmin/ 
administer/ 
LiveUser_Admin/ 
sys-admin/ 
typo3/ 
panel/ 
cpanel/ 
cpanel_file/ 
platz_login/ 
rcLogin/ 
blogindex/ 
formslogin/ 
autologin/ 
support_login/ 
meta_login/ 
manuallogin/ 
simpleLogin/ 
loginflat/ 
utility_login/ 
showlogin/ 
memlogin/ 
login-redirect/ 
sub-login/ 
wp-login/ 
login1/ 
dir-login/ 
login_db/ 
xlogin/ 
smblogin/ 
customer_login/ 
UserLogin/ 
login-us/ 
acct_login/ 
bigadmin/ 
project-admins/ 
phppgadmin/ 
pureadmin/ 
sql-admin/ 
radmind/ 
openvpnadmin/ 
wizmysqladmin/ 
vadmind/ 
ezsqliteadmin/ 
hpwebjetadmin/ 
newsadmin/ 
adminpro/ 
Lotus_Domino_Admin/ 
bbadmin/ 
vmailadmin/ 
Indy_admin/ 
ccp14admin/ 
irc-macadmin/ 
banneradmin/ 
sshadmin/ 
phpldapadmin/ 
macadmin/ 
administratoraccounts/ 
admin4_account/ 
admin4_colon/ 
radmind-1/ 
Super-Admin/ 
AdminTools/ 
cmsadmin/ 
SysAdmin2/ 
globes_admin/ 
cadmins/ 
phpSQLiteAdmin/ 
navSiteAdmin/ 
server_admin_small/ 
logo_sysadmin/ 
power_user/ 
system_administration/ 
ss_vms_admin_sm/ 
bb-admin/ 
panel-administracion/ 
instadmin/ 
memberadmin/ 
administratorlogin/ 
adm 
admin_login 
panel-administracion/login 
pages/admin/admin-login 
pages/admin/ 
acceso 
admincp/login 
admincp/ 
adminarea/ 
admincontrol/ 
affiliate 
adm_auth 
memberadmin 
administratorlogin 
modules/admin/ 
administrators 
siteadmin/ 
siteadmin 
adminsite/ 
kpanel/ 
vorod/ 
vorod 
vorud/ 
vorud 
adminpanel/ 
PSUser/ 
secure/ 
webmaster/ 
webmaster 
autologin 
userlogin 
admin_area 
cmsadmin 
security/ 
usr/ 
root/ 
secret/ 
admin/login 
admin/adminLogin 
moderator.php 
moderator.html 
moderator/login 
moderator/admin 
0admin/ 
0manager/ 
aadmin/ 
cgi-bin/login 
login1 
login_admin/ 
login_admin 
login_out/ 
login_out 
login_user 
loginerror/ 
loginok/ 
loginsave/ 
loginsuper/ 
loginsuper 
logout/ 
logout 
secrets/ 
super1/ 
super1 
super_index 
super_login 
supermanager 
superman 
supervise/ 
supervise/Login 
super 
admin1.php 
admin2.php 
yonetim.php 
yonetici.php 
admin/account.php 
admin/index.php 
admin/index.html 
admin/login.php 
admin/home.php 
admin/controlpanel.php 
admin.php 
admin/cp.php 
admin/cp.html 
cp.php 
cp.html 
administrator/index.html 
administrator/index.php 
administrator/login.html 
administrator/login.php 
administrator/account.html 
administrator/account.php 
administrator.php 
administrator.html 
login.php 
modelsearch/login.php 
moderator/login.php 
moderator/login.html 
moderator/admin.php 
moderator/admin.html 
account.php 
account.html 
controlpanel.php 
controlpanel.html 
admincontrol.php 
admincontrol.html 
adminpanel.php 
adminpanel.html 
admin1.asp 
admin2.asp 
yonetim.asp 
yonetici.asp 
admin/account.asp 
admin/index.asp 
admin/login.asp 
admin/home.asp 
admin/controlpanel.asp 
admin.asp 
admin/cp.asp 
cp.asp 
administrator/index.asp 
administrator/login.asp 
administrator/account.asp 
administrator.asp 
login.asp 
modelsearch/login.asp 
moderator.asp 
moderator/login.asp 
moderator/admin.asp 
account.asp 
controlpanel.asp 
admincontrol.asp 
adminpanel.asp 
fileadmin.php 
fileadmin.asp 
fileadmin.html 
administration.php 
administration.html 
sysadmin.php 
sysadmin.html 
sysadmin.asp 
sysadmin/ 
ur-admin.asp 
ur-admin.php 
ur-admin.html 
Server.php 
Server.html 
Server.asp 
administr8.php 
administr8.html 
administr8.asp 
webadmin.php 
webadmin.asp 
webadmin.html 
admins.php 
admins.asp 
admins.html 
WebAdmin/ 
cPanel/ 
server/ 
database_administration/ 
adiministrador/ 
adimin/ 
senha/ 
membros/ 
usuarios/ 
senhas/ 
sff/ 
saff/ 
donos/ 
noticias/ 
not/ 
painel/ 
administracao/ 
key/ 
edit/ 
config/ 
funcoes/ 
sistema/ 
php/ 
net/ 
controle 
controles 
membro 
membros 
acesso 
senha 
usuario 
usuarios 
admistrador 
adimistrador 
painel 
root 
roots 
raiz 
admin/admin.php 
joomla/administrator 
admin_area/admin.php 
admin_area/login.php 
siteadmin/login.php 
siteadmin/index.php 
siteadmin/login.html 
admin/admin.html 
admin_area/index.php 
bb-admin/index.php 
bb-admin/login.php 
bb-admin/admin.php 
admin_area/login.html 
admin_area/index.html 
admincp/index.asp 
admincp/login.asp 
admincp/index.html 
webadmin/index.html 
webadmin/admin.html 
webadmin/login.html 
admin/admin_login.html 
admin_login.html 
panel-administracion/login.html 
nsw/admin/login.php 
webadmin/login.php 
admin/admin_login.php 
admin_login.php 
admin_area/admin.html 
pages/admin/admin-login.php 
admin/admin-login.php 
admin-login.php 
bb-admin/index.html 
bb-admin/login.html 
admin/home.html 
pages/admin/admin-login.html 
admin/admin-login.html 
admin-login.html 
adminLogin.html 
home.html 
rcjakar/admin/login.php 
adminarea/index.html 
adminarea/admin.html 
webadmin/index.php 
webadmin/admin.php 
user.html 
modelsearch/login.html 
adminarea/login.html 
panel-administracion/index.html 
panel-administracion/admin.html 
modelsearch/index.html 
modelsearch/admin.html 
admincontrol/login.html 
adm/index.html 
adm.html 
user.php 
panel-administracion/login.php 
adminLogin.php 
admin/adminLogin.php 
home.php 
adminarea/index.php 
adminarea/admin.php 
adminarea/login.php 
panel-administracion/index.php 
panel-administracion/admin.php 
modelsearch/index.php 
modelsearch/admin.php 
admincontrol/login.php 
adm/admloginuser.php 
admloginuser.php 
admin2/login.php 
admin2/index.php 
adm/index.php 
adm.php 
affiliate.php 
adm_auth.php 
admin.aspx 
admin.cfm 
admin.xhtml 
wp-admin 
admin/account.cfm 
admin/admin.asp 
admin/admin.cfm 
admin/admin_login.asp 
admin/admin_login.cfm 
admin/admin-login.asp 
admin/adminLogin.asp 
admin/admin-login.cfm 
admin/adminLogin.cfm 
admin/controlpanel.cfm 
admin/cp.cfm 
admin/home.cfm 
admin/index.cfm 
admin/login.cfm 
account.cfm 
adm.asp 
adm.cfm 
adm/admloginuser.asp 
adm/admloginuser.cfm 
adm/index.asp 
adm/index.cfm 
adm_auth.asp 
adm_auth.cfm 
admin_area/admin.asp 
admin_area/admin.cfm 
admin_area/index.asp 
admin_area/index.cfm 
admin_area/login.asp 
admin_area/login.cfm 
admin_login.asp 
admin_login.cfm 
admin2.cfm 
admin2/index.asp 
admin2/index.cfm 
admin2/login.asp 
admin2/login.cfm 
adminarea 
adminarea/admin.asp 
adminarea/admin.cfm 
adminarea/index.asp 
adminarea/index.cfm 
adminarea/login.asp 
adminarea/login.cfm 
admincontrol.cfm 
admincontrol/login.asp 
admincontrol/login.cfm 
admincp/index.cfm 
admincp/login.cfm 
administrator.cfm 
administrator/account.cfm 
administrator/index.cfm 
administrator/login.cfm 
administratorlogin.asp 
administratorlogin.cfm 
administratorlogin.php 
adminLogin 
admin-login.asp 
adminLogin.asp 
admin-login.cfm 
adminLogin.cfm 
adminpanel.cfm 
admloginuser.asp 
admloginuser.cfm 
affiliate.asp 
affiliate.cfm 
bb-admin 
bb-admin/admin.asp 
bb-admin/admin.cfm 
bb-admin/index.asp 
bb-admin/index.cfm 
bb-admin/login.asp 
bb-admin/login.cfm 
Clave/ 
controlpanel.cfm 
cp.cfm 
home.asp 
home.cfm 
instadmin 
login.cfm 
memberadmin.asp 
memberadmin.cfm 
memberadmin.php 
modelsearch/admin.asp 
modelsearch/admin.cfm 
modelsearch/index.asp 
modelsearch/index.cfm 
modelsearch/login.cfm 
moderator.cfm 
moderator/admin.cfm 
moderator/login.cfm 
P/W/ 
pages/admin/admin-login.asp 
pages/admin/admin-login.cfm 
panel-administracion 
panel-administracion/admin.asp 
panel-administracion/admin.cfm 
panel-administracion/index.asp 
panel-administracion/index.cfm 
panel-administracion/login.asp 
panel-administracion/login.cfm 
passe/ 
password/ 
Password/ 
PASSWORD/ 
Personal/ 
Senha/ 
Sing/ 
siteadmin/index.asp 
siteadmin/index.cfm 
siteadmin/login.asp 
siteadmin/login.cfm 
usager/ 
Usager/ 
user.asp 
user.cfm 
username/ 
Username/ 
USERNAME/ 
Usuario/ 
webadmin.cfm 
webadmin/admin.asp 
webadmin/admin.cfm 
webadmin/index.asp 
webadmin/index.cfm 
webadmin/login.asp 
webadmin/login.cfm 
/user.asp 
/panel.asp 
/admin/login.htm 
/administratorlogin.php 
/cp.asp 
/admin.php 
/administrators.php 
/relogin.htm 
/log-in.asp 
/controlpanel.asp 
/vadmind/ 
/log-in.php 
/authadmin.php 
/xlogin/ 
/server_admin_small/ 
/admincp/login.php 
/adm_auth.asp 
/checkadmin.asp 
/adminpro/ 
/loginflat/ 
/bb-admin/login.asp 
/news_detail.php 
/Indy_admin/ 
/adminitem.asp 
/vorod.php 
/moderator/login.asp 
/login1/ 
/irc-macadmin/ 
/superuser.php 
/pureadmin/ 
/formslogin/ 
/adminitems/ 
/sysadm/ 
/0manager/ 
/Server/ 
/phpldapadmin/ 
/yonetim.html 
/adminLogin/ 
/vorod/ 
/sysadm.asp 
/administrator/ 
/loginok/ 
/root/ 
/yonetim.php 
/loginphp 
/index.swf 
/loginsave/ 
/admin1.htm 
/dir-login/ 
/wp-login.php 
/superuserasp 
/moderator/admin.asp 
/adminsite/ 
/logoutasp 
/access/ 
/cpanel_file/ 
/sysadmins/ 
/moderator.php 
/relogin.php 
/users/ 
/smblogin/ 
/navSiteAdmin/ 
/isadmin.php 
/sign-in.php 
/memlogin/ 
/phppgadmin/ 
/management.asp 
/js/jquery-1.4.2.js 7 http://www.mirandam.com/panel/about_edit.php 
/instadmin/ 
/bb-admin/admin.html 
/0admin/ 
/affiliate.php 
/meta_login/ 
/signin.php 
/superuser.asp 
/loginsuper/ 
/vorod.asp 
/aadmin/ 
/ur-admin.php 
/yonetici.asp 
/admin/controlpanel.asp 
/administr8.asp 
/signin.asp 
/administration/ 
/admin2.asp 
/blogindex/ 
/ur-admin/ 
/admincontrol.php 
/cgi-bin/loginasp 
/js/%20id= 
/cgi-bin/loginphp 
/adm.php 
/admin_login.asp 
/administration.php 
/login-us/ 
/supermanagerasp 
/moderator/admin.php 
/admin/account.php 
/Server.asp 
/useradmin/ 
/adminlogin.php 
/bigadmin/ 
/moderator.asp 
/login_adminasp 
/authentication.asp 
/power_user/ 
/modules/admin/ 
/admin1.asp 
/platz_login/ 
/manager/ 
/logout/ 
/manage/ 
/admin/admin.asp 
/moderator/login.php 
/pages/admin/admin-login.php 
/fileadmin.asp 
/wp-admin/ 
/logo_sysadmin/ 
/admin/adminLogin.htm 
/bb-admin/admin.asp 
/pages/admin/ 
/processlogin.php 
/loginsuperphp 
/super1php 
/uvpanel/ 
/macadmin/ 
/system_administration/ 
/admin/cp.php 
/admin4_account/ 
/sysadmin.php 
/control.php 
/supermanphp 
/super_indexasp 
/admin/adminLogin.php 
/panel-administracion/login.php 
/admin/account.html 
/admins.php 
/log_in.php 
/admins.asp 
/radmind-1/ 
/sysadm.php 
/staradmin/ 
/login_db/ 
/userlogin.php 
/secrets/ 
/accounts.php 
/security/ 
/login/ 
/manage.php 
/panel/js/jquery.maskedinput.js 
/login_userasp 
/vmailadmin/ 
/globes_admin/ 
/fileadmin/ 
/login_outphp 
/admin4_colon/ 
/superphp 
/admin/ 
/vorud.asp 
/admin_login.php 
/manager.php 
/admin/account.asp 
/admin_area.asp 
/admin.html 
/usr/ 
/administr8.php 
/SysAdmin2/ 
/adminitem.php 
/management/ 
/project-admins/ 
/typo3/ 
/admin.htm 
/admin/home.asp 
/vorud.php 
/admins/ 
/accounts/ 
/super_loginphp 
/super_indexphp 
/adminpanel.php 
/memberadmin/ 
/access.asp 
/superuserphp 
/system-administration/ 
/pages/admin/admin-login.asp 
/panel-administracion/login.asp 
/sign_in.php 
/super_loginasp 
/moderator.html 
/log_in/ 
/autologin.php 
/sysadmin.asp 
/supermanasp 
/adminitems.php 
/admin/cp.asp 
/acceso.php 
/login-redirect/ 
/auth.php 
/login.asp 
/Database_Administration/ 
/webadmin.asp 
/modelsearch/login.asp 
/cmsadmin/ 
/admincp/login.asp 
/phpSQLiteAdmin/ 
/login_admin/ 
/ServerAdministrator/ 
/admin-login.asp 
/letmein.asp 
/member/ 
/acct_login/ 
/loginsuperasp 
/manage.asp 
/sign_in/ 
/LiveUser_Admin/ 
/administratoraccounts/ 
/utility_login/ 
/administrator.php 
/js/url.slice(0,off) 
/secure/ 
/administrator/login.asp 
/checklogin.asp 
/admin_area/login.php 
/authentication.php 
/UserLogin/ 
/webadmin/ 
/rcLogin/ 
/sub-login/ 
/authenticate.asp 
/login.html 
/admin/admin-login.php 
/ss_vms_admin_sm/ 
/SysAdmin/ 
/secret/ 
/login1php 
/fileadmin.php 
/controlpanel.php 
/members.asp 
/login1asp 
/directadmin/ 
/adminlogin.asp 
/undefined 2 http://mirandam.com/shop.php 
/affiliate.asp 
/admin/home.php 
/admin.asp 
/superuser/ 
/Server.php 
/cpanel/ 
/cp.php 
/customer_login/ 
/access.php 
/administratie/ 
/control.asp 
/autologin/ 
/wp-login/ 
/administrator/login.php 
/admin/admin-login.asp 
/openvpnadmin/ 
/FCKeditor/editor/images/anchor.gif 
/checklogin.php 
/admin1.html 
/siteadmin.php 
/yonetim.asp 
/supervise/Loginasp 
/adminitem/ 
/admin/controlpanel.php 
/authuser.php 
/modelsearch/login.php 
/ur-admin.asp 
/showlogin/ 
/webmaster.php 
/letmein.php 
/admin-login.php 
/sign_in.asp 
/sshadmin/ 
/loginasp 
/checkadmin.php 
/letmein/ 
/panel.php 
/simpleLogin/ 
/control/ 
/log-in/ 
/moderator/ 
/admin/login.asp 
members/ 
/admin_area.php 
/logoutphp 
/administrator/account.php 
/bb-admin/ 
/administr8/ 
/relogin.asp 
/cmsadmin.asp 
/member.php 
/admin/adminLogin.html 
/adminpanel/ 
/supermanagerphp 
/panel-administracion/ 
/relogin.html 
/sign-in.asp 
/adm_auth.php 
/ezsqliteadmin/ 
/adm.asp 
/member.asp 
/admin1.php 
/radmind/ 
/login_outasp 
/admin2.php 
/admin_area/ 
/sql-admin/ 
/administratorlogin/ 
/admin/login.php 
/admin/controlpanel.htm 
/processlogin.asp 
/administrators.asp 
/admincp/ 
/Super-Admin/ 
/kpanel/ 
/log_in.asp 
/webadmin.php 
/accounts.asp 
/checkuser.php 
/ccp14admin/ 
/newsadmin/ 
/check.asp 
/manuallogin/ 
/administrators/ 
/autologin.asp 
/checkuser.asp 
/acceso.asp 
/adminitems.asp 
/auth.asp 
/superasp 
/login_userphp 
/PSUser/ 
/siteadmin.asp 
/admin_area/login.asp 
/wizmysqladmin/ 
/memberadmin.php 
/userlogin.asp 
/siteadmin/ 
/adminarea/ 
/adm/ 
/users.php 
/supervise/Loginphp 
/manager.asp 
/users.asp 
/login.htm 
/cmsadmin.php 
/administration.asp 
/signin/ 
/admin_area/admin.php 
/admincontrol.asp 
/supervise/ 
/adminpanel.asp 
/super1asp 
/login_adminphp 
/webmaster/ 
/sign-in/ 
/bbadmin/ 
/authadmin.asp 
/admin/adminLogin.asp 
/hpwebjetadmin/ 
/super1/ 
/support_login/ 
/login_out/ 
/yonetici.html 
/administratorlogin.asp 
/bb-admin/login.php 
/management.php 
/administer/ 
/yonetici.php 
/sys-admin/ 
/Lotus_Domino_Admin/ 
/members.php 
/administrivia/ 
/authenticate.php 
/banneradmin/ 
/user/ 
/AdminTools/ 
/admin/controlpanel.html 
/webmaster.asp 
/administrator.asp 
/authuser.asp 
/cadmins/ 
/superman/ 
/admincontrol/ 
/bb-admin/admin.php 
/supervisor/ 
/pgadmin/ 
/loginerror/ 
/admin/admin_login.php 
/isadmin.asp 
/check.php 
/admin/admin_login.asp 
/admin_area/admin.asp 
/user.php 
/admin/admin.php 
/admin/login.html 
/admin2.html 
/admin1/ 
/vorud/ 
/memberadmin.asp 
/administrator/account.asp 
?a=login 
processlogin.php 
FCKeditor/editor/images/anchor.gif 
acceso.asp 
acceso.php 
access.asp 
access.php 
accounts.asp 
accounts.php 
adminlogin.php 
admin_area.asp 
admin_area.php 
admincp/login.php 
administration.asp 
administrators.asp 
administrators.php 
adminitem.asp 
adminitem.php 
adminitems.asp 
adminitems.php 
adminlogin.asp 
auth.asp 
auth.php 
authadmin.asp 
authadmin.php 
authenticate.asp 
authenticate.php 
authentication.asp 
authentication.php 
authuser.asp 
authuser.php 
autologin.asp 
autologin.php 
blog/wp-login.asp 
cgi-bin/loginasp 
cgi-bin/loginphp 
check.asp 
check.php 
checkadmin.asp 
checkadmin.php 
checklogin.asp 
checklogin.php 
checkuser.asp 
checkuser.php 
cmsadmin.asp 
cmsadmin.php 
control.asp 
control.php 
index.swf 
isadmin.asp 
isadmin.php 
js/%20id= 
js/url.slice(0,off) 
letmein.asp 
letmein.php 
log-in.asp 
log-in.php 
log_in.asp 
log_in.php 
login1asp 
login1php 
login_adminasp 
login_adminphp 
login_outasp 
login_outphp 
login_userasp 
login_userphp 
loginasp 
loginphp 
loginsuperasp 
loginsuperphp 
logoutasp 
logoutphp 
manage.asp 
manage.php 
management.asp 
management.php 
manager.asp 
manager.php 
member.asp 
member.php 
members.asp 
members.php 
news_detail.php 
panel.asp 
panel.php 
panel/js/jquery.maskedinput.js 
processlogin.asp 
relogin.asp 
relogin.php 
shop.php 
sign-in.asp 
sign-in.php 
sign_in.asp 
sign_in.php 
signin.asp 
signin.php 
siteadmin.asp 
siteadmin.php 
super1asp 
super1php 
super_indexasp 
super_indexphp 
super_loginasp 
super_loginphp 
superasp 
supermanagerasp 
supermanagerphp 
supermanasp 
supermanphp 
superphp 
superuser.asp 
superuser.php 
superuserasp 
superuserphp 
supervise/Loginasp 
supervise/Loginphp 
sysadm.asp 
sysadm.php 
user/admin.asp 
userlogin.asp 
userlogin.php 
users.asp 
users.php 
users/admin.asp 
vorod.asp 
vorod.php 
vorud.asp 
vorud.php 
webmaster.asp 
webmaster.php 

admin1.php 
admin1.html 
admin2.php 
admin2.html 
yonetim.php 
yonetim.html 
yonetici.php 
yonetici.html 
ccms/ 
ccms/login.php 
ccms/index.php 
maintenance/ 
webmaster/ 
adm/ 
configuration/ 
configure/ 
websvn/ 
admin/ 
admin/account.php 
admin/account.html 
admin/index.php 
admin/index.html 
admin/login.php 
admin/login.html 
admin/home.php 
admin/controlpanel.html 
admin/controlpanel.php 
admin.php 
admin.html 
admin/cp.php 
admin/cp.html 
cp.php 
cp.html 
administrator/ 
administrator/index.html 
administrator/index.php 
administrator/login.html 
administrator/login.php 
administrator/account.html 
administrator/account.php 
administrator.php 
administrator.html 
login.php 
login.html 
modelsearch/login.php 
moderator.php 
moderator.html 
moderator/login.php 
moderator/login.html 
moderator/admin.php 
moderator/admin.html 
moderator/ 
account.php 
account.html 
controlpanel/ 
controlpanel.php 
controlpanel.html 
admincontrol.php 
admincontrol.html 
adminpanel.php 
adminpanel.html 
admin1.asp 
admin2.asp 
yonetim.asp 
yonetici.asp 
admin/account.asp 
admin/index.asp 
admin/login.asp 
admin/home.asp 
admin/controlpanel.asp 
admin.asp 
admin/cp.asp 
cp.asp 
administrator/index.asp 
administrator/login.asp 
administrator/account.asp 
administrator.asp 
login.asp 
modelsearch/login.asp 
moderator.asp 
moderator/login.asp 
moderator/admin.asp 
account.asp 
controlpanel.asp 
admincontrol.asp 
adminpanel.asp 
fileadmin/ 
fileadmin.php 
fileadmin.asp 
fileadmin.html 
administration/ 
administration.php 
administration.html 
sysadmin.php 
sysadmin.html 
phpmyadmin/ 
sysadmin.asp 
sysadmin/ 
ur-admin.asp 
ur-admin.php 
ur-admin.html 
ur-admin/ 
Server.php 
Server.html 
Server.asp 
Server/ 
wp-admin/ 
administr8.php 
administr8.html 
administr8/ 
administr8.asp 
webadmin/ 
webadmin.php 
webadmin.asp 
webadmin.html 
administratie/ 
admins/ 
admins.php 
admins.asp 
admins.html 
administrivia/ 
Database_Administration/ 
WebAdmin/ 
useradmin/ 
sysadmins/ 
admin1/ 
system-administration/ 
administrators/ 
pgadmin/ 
directadmin/ 
staradmin/ 
ServerAdministrator/ 
SysAdmin/ 
administer/ 
LiveUser_Admin/ 
sys-admin/ 
typo3/ 
panel/ 
cpanel/ 
cPanel/ 
cpanel_file/ 
platz_login/ 
rcLogin/ 
blogindex/ 
formslogin/ 
autologin/ 
support_login/ 
meta_login/ 
manuallogin/ 
simpleLogin/ 
loginflat/ 
utility_login/ 
showlogin/ 
memlogin/ 
members/ 
login-redirect/ 
sub-login/ 
wp-login/ 
login1/ 
dir-login/ 
login_db/ 
xlogin/ 
smblogin/ 
customer_login/ 
UserLogin/ 
login-us/ 
acct_login/ 
admin_area/ 
bigadmin/ 
project-admins/ 
phppgadmin/ 
pureadmin/ 
sql-admin/ 
radmind/ 
openvpnadmin/ 
wizmysqladmin/ 
vadmind/ 
ezsqliteadmin/ 
hpwebjetadmin/ 
newsadmin/ 
adminpro/ 
Lotus_Domino_Admin/ 
bbadmin/ 
vmailadmin/ 
Indy_admin/ 
ccp14admin/ 
irc-macadmin/ 
banneradmin/ 
sshadmin/ 
phpldapadmin/ 
macadmin/ 
administratoraccounts/ 
admin4_account/ 
admin4_colon/ 
radmind-1/ 
Super-Admin/ 
AdminTools/ 
cmsadmin/ 
SysAdmin2/ 
globes_admin/ 
cadmins/ 
phpSQLiteAdmin/ 
navSiteAdmin/ 
server_admin_small/ 
logo_sysadmin/ 
server/ 
database_administration/ 
power_user/ 
system_administration/ 
ss_vms_admin_sm/ 
adminarea/ 
bb-admin/ 
adminLogin/ 
panel-administracion/ 
instadmin/ 
memberadmin/ 
administratorlogin/ 
admin/admin.php 
admin_area/admin.php 
admin_area/login.php 
siteadmin/login.php 
siteadmin/index.php 
siteadmin/login.html 
admin/admin.html 
admin_area/index.php 
bb-admin/index.php 
bb-admin/login.php 
bb-admin/admin.php 
admin_area/login.html 
admin_area/index.html 
admincp/index.asp 
admincp/login.asp 
admincp/index.html 
webadmin/index.html 
webadmin/admin.html 
webadmin/login.html 
admin/admin_login.html 
admin_login.html 
panel-administracion/login.html 
nsw/admin/login.php 
webadmin/login.php 
admin/admin_login.php 
admin_login.php 
admin_area/admin.html 
pages/admin/admin-login.php 
admin/admin-login.php 
admin-login.php 
bb-admin/index.html 
bb-admin/login.html 
bb-admin/admin.html 
admin/home.html 
pages/admin/admin-login.html 
admin/admin-login.html 
admin-login.html 
admin/adminLogin.html 
adminLogin.html 
home.html 
rcjakar/admin/login.php 
adminarea/index.html 
adminarea/admin.html 
webadmin/index.php 
webadmin/admin.php 
user.html 
modelsearch/login.html 
adminarea/login.html 
panel-administracion/index.html 
panel-administracion/admin.html 
modelsearch/index.html 
modelsearch/admin.html 
admincontrol/login.html 
adm/index.html 
adm.html 
user.php 
panel-administracion/login.php 
wp-login.php 
adminLogin.php 
admin/adminLogin.php 
home.php 
adminarea/index.php 
adminarea/admin.php 
adminarea/login.php 
panel-administracion/index.php 
panel-administracion/admin.php 
modelsearch/index.php 
modelsearch/admin.php 
admincontrol/login.php 
adm/admloginuser.php 
admloginuser.php 
admin2/login.php 
admin2/index.php 
adm/index.php 
adm.php 
affiliate.php 
adm_auth.php 
memberadmin.php 
administratorlogin.php 
admin/admin.asp 
admin_area/admin.asp 
admin_area/login.asp 
admin_area/index.asp 
bb-admin/index.asp 
bb-admin/login.asp 
bb-admin/admin.asp 
pages/admin/admin-login.asp 
admin/admin-login.asp 
admin-login.asp 
user.asp 
webadmin/index.asp 
webadmin/admin.asp 
webadmin/login.asp 
admin/admin_login.asp 
admin_login.asp 
panel-administracion/login.asp 
adminLogin.asp 
admin/adminLogin.asp 
home.asp 
adminarea/index.asp 
adminarea/admin.asp 
adminarea/login.asp 
panel-administracion/index.asp 
panel-administracion/admin.asp 
modelsearch/index.asp 
modelsearch/admin.asp 
admincontrol/login.asp 
adm/admloginuser.asp 
admloginuser.asp 
admin2/login.asp 
admin2/index.asp 
adm/index.asp 
adm.asp 
affiliate.asp 
adm_auth.asp 
memberadmin.asp 
administratorlogin.asp 
siteadmin/login.asp 
siteadmin/index.asp 
ADMIN/ 
paneldecontrol/ 
login/ 
cms/ 
admon/ 
ADMON/ 
ADMIN/login.php 
panelc/ 
ADMIN/login.html";
function template() {
echo '
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Admin page Finder by k[N]i[g]Ht</title>
<style type="text/css">
body{
        background: #000;
        margin: 0;
        padding: 0;
        padding-top: 10px;
        color: #FFF;
        font-family: Calibri;
        font-size: 13px;
}
a{
        color: #FFF;
        text-decoration: none;
        font-weight: bold;
}
.wrapper{
        width: 1000px;
        margin: 0 auto;
}
.tube{
        padding: 10px;
}
.red{
        width: 998px;
        border: 1px solid #e52224;
        background: #191919;
        color: #e52224
}
.red input{
        background: #000;
        border: 1px solid #e52224;
        color: #FFF;
}
.blue{
        float: left;
        width: 1000px;
        border: 1px solid #1d7fc3;
        background: #191919;
        color: #1d7fc3;
}
.green{
        float: left;
        width: 1000px;
        border: 1px solid #5fd419;
        background: #191919;
        color: #5fd419;
}
</style>
<script type="text/javascript">
<!--
function insertcode($text, $place, $replace)
{
        var $this = $text;
        var logbox = document.getElementById($place);
        if($replace == 0)
                document.getElementById($place).innerHTML = logbox.innerHTML+$this;
        else
                document.getElementById($place).innerHTML = $this;
//document.getElementById("helpbox").innerHTML = $this;
}
-->
</script>
</head>
<body>
<br />
<br />
<div class="wrapper">
<div class="red">
<div class="tube">
<form action="" method="post" name="xploit_form">
URL:<br /><input type="text" name="xploit_url" value="'.$_POST['xploit_url'].'" style="width: 100%;" /><br /><br />
404string:<br /><input type="text" name="xploit_404string" value="'.$_POST['xploit_404string'].'" style="width: 100%;" /><br /><br />
<span style="float: right;"><input type="submit" name="xploit_submit" value="go for it" align="right" /></span>
</form>
<br />
</div> <!-- /tube -->
</div> <!-- /red -->
<br />
<div class="green">
<div class="tube" id="rightcol">
Verificat: <span id="verified">0</span> / <span id="total">0</span><br />
Found ones:<br />
</div> <!-- /tube -->
</div> <!-- /green -->
<br clear="all" /><br />
<div class="blue">
<div class="tube" id="logbox">
<br />
<br />
Admin page Finder [v0.2]<br />
bY kNigHt<br />
</div> <!-- /tube -->
</div> <!-- /blue -->
</div> <!-- /wrapper -->
<br clear="all">';
}
function show($msg, $br=1, $stop=0, $place='logbox', $replace=0) {
        if($br == 1) $msg .= "<br />";
        echo "<script type=\"text/javascript\">insertcode('".$msg."', '".$place."', '".$replace."');</script>";
        if($stop == 1) exit;
        @flush();@ob_flush();
}
function check($x, $front=0) {
        global $_POST,$site,$false;
        if($front == 0) $t = $site.$x;
        else $t = 'http://'.$x.'.'.$site.'/';
        $headers = get_headers($t);
        if (!eregi('200', $headers[0])) return 0;
        $data = @file_get_contents($t);
        if($_POST['xploit_404string'] == "") if($data == $false) return 0;
        if($_POST['xploit_404string'] != "") if(strpos($data, $_POST['xploit_404string'])) return 0;
        return 1;
}
       
// --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
template();
if(!isset($_POST['xploit_url'])) die;
if($_POST['xploit_url'] == '') die;
$site = $_POST['xploit_url'];
if ($site[strlen($site)-1] != "/") $site .= "/";
if($_POST['xploit_404string'] == "") $false = @file_get_contents($site."d65897f5380a21a42db94b3927b823d56ee1099a-this_can-t_exist.html");
$list['end'] = str_replace("\r", "", $list['end']);
$list['front'] = str_replace("\r", "", $list['front']);
$pathes = explode("\n", $list['end']);
$frontpathes = explode("\n", $list['front']);
show(count($pathes)+count($frontpathes), 1, 0, 'total', 1);
$verificate = 0;
foreach($pathes as $path) {
        show('Checking '.$site.$path.' : ', 0, 0, 'logbox', 0);
        $verificate++; show($verificate, 0, 0, 'verified', 1);
        if(check($path) == 0) show('not found', 1, 0, 'logbox', 0);
        else{
                show('<span style="color: #00FF00;"><strong>found</strong></span>', 1, 0, 'logbox', 0);
                show('<a href="'.$site.$path.'">'.$site.$path.'</a>', 1, 0, 'rightcol', 0);
        }
}
preg_match("/\/\/(.*?)\//i", $site, $xx); $site = $xx[1];
if(substr($site, 0, 3) == "www") $site = substr($site, 4);
foreach($frontpathes as $frontpath) {
        show('Checking http://'.$frontpath.'.'.$site.'/ : ', 0, 0, 'logbox', 0);
        $verificate++; show($verificate, 0, 0, 'verified', 1);
        if(check($frontpath, 1) == 0) show('not found', 1, 0, 'logbox', 0);
        else{
                show('<span style="color: #00FF00;"><strong>found</strong></span>', 1, 0, 'logbox', 0);
                show('<a href="http://'.$frontpath.'.'.$site.'/">'.$frontpath.'.'.$site.'</a>', 1, 0, 'rightcol', 0);
        }
       
}
?>
